name: Meaningless Nonsense
markdown: kramdown
url: "https://jasmineouo.github.io/Blog"
permalink: /:title
defaults:
  - scope:
      path: "resources/images/polaroids"
    values:
      image: true
      
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed
  - searchyll

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .vs/slnx.sqlite

elasticsearch:
    url: https://7a16e3rgmw:ik0iq34897@blog-data-7838678728.us-east-1.bonsaisearch.net  
    index_name: Blog_Data 
