name: Meaningless Nonsense
markdown: kramdown
url: "https://jasmineouo.github.io/Blog"
permalink: /:title
defaults:
  - scope:
      path: "resources/images/polaroids"
    values:
      image: true
repository: JasmineOuO/Blog
staticman:
  branch: "master"
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed
    #- searchyll

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .vs/slnx.sqlite
  - node_modules

    #elasticsearch:
    #index_name: blog
    #url: https://j9a2d7lhet:8vldytub88@blog-2086566074.us-east-1.bonsaisearch.net
